application: projectid # Your application ID
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /(.*\.(pdf|gif|png|jpg|ico|js|css))
  static_files: \1
  upload: (.*\.(pdf|gif|png|jpg|ico|js|css))

- url: .*
  script: main.app
  secure: always

libraries:
- name: webapp2
  version: latest
